### ISSUE TITLE
Pull request and repository creation flow

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/git-controller#16]
## Scenario 1

During Project creation, an incoming request is provided to git-controller to create a Repository containing configured directories and code ownership (code owners still need to be set up ).

The repository request might look something like this:

```yaml
apiVersion: mpas.ocm.software/v1alpha1
kind: Repository
metadata:
  name: repository-sample
spec:
  credentials:
    secretRef:
      name: github-creds
  owner: Skarlso
  provider: github
  repositoryName: new-repository-1
```

## Scenario 2

Some object generates an output that needs to be synced into a Git Repositroy. This request contains the source for an object which will fetch the appropriate snapshot. From here, there are two options.

### AutomaticPullRequest creation is enabled

If the automatic pull request creation is enabled, syncer will take the changes, push them into a generated branch and create a pull request to the base branch for the changes.

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Sync
metadata:
  name: git-sample
  namespace: ocm-system
spec:
  commitTemplate:
    email: <email>
    message: "Update made from git-controller"
    name: Gergely Brautigam
  # branch: main # note that this is disabled, during automatic pull request creation it is ignored.
  interval: 10m0s
  subPath: ./application/podinfo
  repositoryRef:
    name: git-repository
  componentRef:
    name: ocm-test-component
    namespace: ocm-system
  snapshotRef: # updated later to be a SourceRef
    name: ocm-test-snapshot
    namespace: ocm-system
  automaticPullRequestCreation: true
  pullRequestTemplate:
    base: main
    title: title
    description: description
```

### AutomaticPullRequest creation is disabled

In this case, the syncer will plain push the contents of the source object into a given branch. No other action is taken.

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Sync
metadata:
  name: git-sample
  namespace: ocm-system
spec:
  branch: main
  commitTemplate:
    email: <email>
    message: "Update made from git-controller"
    name: Gergely Brautigam
  interval: 10m0s
  subPath: ./application/podinfo
  repositoryRef:
    name: git-repository
  componentRef:
    name: ocm-test-component
    namespace: ocm-system
  snapshotRef:
    name: ocm-test-snapshot
    namespace: ocm-system

```
